### ISSUE TITLE
Not seeing the UI

### ISSUE THREAD

**Issue by SilentKnightOwl** [flurb18/AgentOoba#16]
I've installed it, and it shows up in the interface mode as checked, but there's nothing new in the text generation page.

**Comment by privatedownloads** [comment]
same

**Comment by flurb18** [comment]
It should be in a tab at the top

**Comment by SilentKnightOwl** [comment]
Ah, I just had to update the text generation webui. It's now a tab

**Comment by privatedownloads** [comment]
> It should be in a tab at the top

For some reason, I swear I didn’t see that the first time I ran it hahaha, it works great though, very cool, I’ve been having issues getting it to use wikipedia and stuff though do you have any tips?

**Comment by ramzeez88** [comment]
is there meant to be a new UI under the original one in the text generation tab ? if so i don't see one, just as usual interface.

**Comment by rombodawg** [comment]
Yea the ui doesnt show up for me, even after updating

**Comment by rombodawg** [comment]
Update, i had to load the extension in the python script and not in the ui otherwise it wouldnt work
