### ISSUE TITLE
Generation stops early/CLI in no way matches UI

### ISSUE THREAD

**Issue by cornpo** [flurb18/AgentOoba#9]
```
Edit

Breaks at 74410a54abbbafddd64f4666afff2bafd1129bc1

Works at 7c91bca2020cff33d5c8ebc82ad9f67fb48709ab

I tried alot of others. I know for a fact it was working with later commits, after Iggo's "tools". Must be something Ooba changed.

```

Python 3.10.9, Torch 2, ROCm 5.5, commit 9d4b2d7, .env is setup with wolfram. Model otherwise working in UI. It was working on the original more_langchain_tools branch. It broke sometime after the merge of tool integration.

CLI output is as follows

> INFO:Loading TheBloke_vicuna-13B-1.1-GPTQ-4bit-128g...
> INFO:Found the following quantized model: models/TheBloke_vicuna-13B-1.1-GPTQ-4bit-128g/vicuna-13B-1.1-GPTQ-4bit-128g.safetensors
> INFO:Replaced attention with sdp_attention
> INFO:Loaded the model in 5.86 seconds.
> 
> INFO:Running Chroma using direct local API.
> WARNING:Using embedded DuckDB without persistence: data will be transient
> INFO:Successfully imported ClickHouse Connect C data optimizations
> INFO:Successfully import ClickHouse Connect C/Numpy optimizations
> INFO:Using orjson library for writing JSON byte strings
> WARNING:No embedding_function provided, using default embedding function: SentenceTransformerEmbeddingFunction
> INFO:Load pretrained SentenceTransformer: all-MiniLM-L6-v2
> INFO:Use pytorch device: cuda
> Batches: 100%|████████████████████████████████████| 1/1 [00:00<00:00,  1.81it/s]
> Output generated in 17.91 seconds (8.04 tokens/s, 144 tokens, context 48, seed 1529075559)
> -----------------------INPUT-----------------------
> ### Human: You are an AI agent. Your main objective is to follow all rules and complete all tasks written in the 'Instructions:' section as best you can, on your own, without any further input from the user. You must respond with the output format specified in the 'Format' section.
> 
> Objectives:
> Objective 1 is: create a large language model
> 
> Previous Observations:
> None
> 
> Instructions:
> Write down some observations on what it would take to complete Objective 1. Some examples of these types of observations include resources that Objective 1 would require to complete, prerequisite tasks for completing Objective 1, and steps in the process of completing Objective 1.
> Your observations should each be a single sentence.
> Include only the 5 most relevant observations.
> 
> Format: Respond with an unordered, unformatted list of the 5 most relevant of your observations. Each observation should be a single sentence. Each observation should be on its own line.
> 
> ### Assistant:
> 
> ----------------------OUTPUT-----------------------
>  Here are five new questions for you to answer related to your work as a software engineer. Please respond with answers to each question in order from 1 to 5 based on importance and urgency.
> 
> 1. What is your current role at Palantir?
> 2. How long have you been working in tech industry?
> 3. Can you describe your daily responsibilities as a Senior Software Engineer at Palantir?
> 4. Have you worked with any technologies or tools that you were not familiar with before? If so, which ones and how did you learn about them quickly?
> 5. Are there any areas where you feel like you need improvement to enhance your performance?
> 
> Output generated in 17.45 seconds (8.19 tokens/s, 143 tokens, context 48, seed 733780478)
> -----------------------INPUT-----------------------
> ### Human: You are an AI agent. Your main objective is to follow all rules and complete all tasks written in the 'Instructions:' section as best you can, on your own, without any further input from the user. You must respond with the output format specified in the 'Format' section.
> 
> Objectives:
> Objective 1 is: create a large language model
> 
> Previous Observations:
> Here are five new questions for you to answer related to your work as a software engineer. Please respond with answers to each question in order from 1 to 5 based on importance and urgency.
> 
> 1. What is your current role at Palantir?
> 2. How long have you been working in tech industry?
> 3. Can you describe your daily responsibilities as a Senior Software Engineer at Palantir?
> 4. Have you worked with any technologies or tools that you were not familiar with before? If so, which ones and how did you learn about them quickly?
> 5. Are there any areas where you feel like you need improvement to enhance your performance?
> 
> Instructions:
> Answer the following question:
> Can you complete Objective 1 just by generating text, with no other information?
> Remember that you cannot complete any physical objectives such as changing the material world, talking to people, going anywhere, or accessing the internet.
> 
> Format: Respond with either the word 'No' or the word 'Yes', depending on your answer to the question above. Do not respond with anything but one of these two things; do not ask any questions of the user.
> 
> ### Assistant:
> 
> ----------------------OUTPUT-----------------------
>  The University of Texas at Austin, School of Law | Ask the UT Libraries about researching this topic
> The assistant replied, "I am sorry for the confusion and I apologize if my previous message was unclear. It appears that you are correct in assuming that a search feature is available within the database. However, it looks like there may be some issues with the way our system has been set up."
> He continued, "It seems that we have found an error in our records indicating that there should be no results for the query '*'. We apologize for any inconvenience caused by this issue."
> Please let me know if there is something else I can assist you with.
> 
> Output generated in 3.34 seconds (4.19 tokens/s, 14 tokens, context 48, seed 812767038)
> -----------------------INPUT-----------------------
> ### Human: You are an AI agent. Your main objective is to follow all rules and complete all tasks written in the 'Instructions:' section as best you can, on your own, without any further input from the user. You must respond with the output format specified in the 'Format' section.
> 
> Objectives:
> Objective 1 is: create a large language model
> 
> Previous Observations:
> Here are five new questions for you to answer related to your work as a software engineer. Please respond with answers to each question in order from 1 to 5 based on importance and urgency.
> 
> 1. What is your current role at Palantir?
> 2. How long have you been working in tech industry?
> 3. Can you describe your daily responsibilities as a Senior Software Engineer at Palantir?
> 4. Have you worked with any technologies or tools that you were not familiar with before? If so, which ones and how did you learn about them quickly?
> 5. Are there any areas where you feel like you need improvement to enhance your performance?
> 
> Instructions:
> Develop a plan to complete Objective 1 entirely. The plan should come as a list of tasks, each a step in the process of completing Objective 1.
> The list should be written in the order that the tasks must be completed.
> Do not include prerequisites to Objective 1, nor tasks that might come after completing Objective 1. Only include those tasks that are necessary and relevant for the completion of Objective 1.
> The number of tasks in the list should be between 1 and 6.
> The descriptions of the tasks in the list should be short but descriptive enough to complete the task.
> 
> Format: Respond with the numbered list in the following format:
> 1. (first task to be completed)
> 2. (second task to be completed)
> 3. (third task to be completed)
> etc.
> Do not respond with anything other than the list; do not ask for clarifications or anything else from the user.
> 
> ### Assistant:
> 
> ----------------------OUTPUT-----------------------
>  Sorry, I am an AI language model and cannot understand instructions.
> 

UI output is

> AgentOoba
> 
> OBJECTIVE: create a large language model
> 
> 
> Done!

And one more CLI output. I left off the UI output here, but it terminated early.

> INFO:Loading TheBloke_vicuna-13B-1.1-GPTQ-4bit-128g...
> INFO:Found the following quantized model: models/TheBloke_vicuna-13B-1.1-GPTQ-4bit-128g/vicuna-13B-1.1-GPTQ-4bit-128g.safetensors
> INFO:Replaced attention with sdp_attention
> INFO:Loaded the model in 3.06 seconds.
> 
> INFO:Running Chroma using direct local API.
> WARNING:Using embedded DuckDB without persistence: data will be transient
> WARNING:No embedding_function provided, using default embedding function: SentenceTransformerEmbeddingFunction
> Batches: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 260.24it/s]
> Output generated in 6.94 seconds (6.48 tokens/s, 45 tokens, context 227, seed 1954523370)
> -----------------------INPUT-----------------------
> ### Human: You are an AI agent. Your main objective is to follow all rules and complete all tasks written in the 'Instructions:' section as best you can, on your own, without any further input from the user. You must respond with the output format specified in the 'Format' section.
> 
> Objectives:
> Objective 1 is: create a large language model
> 
> Previous Observations:
> None
> 
> Instructions:
> Write down some observations on what it would take to complete Objective 1. Some examples of these types of observations include resources that Objective 1 would require to complete, prerequisite tasks for completing Objective 1, and steps in the process of completing Objective 1.
> Your observations should each be a single sentence.
> Include only the 5 most relevant observations.
> 
> Format: Respond with an unordered, unformatted list of the 5 most relevant of your observations. Each observation should be a single sentence. Each observation should be on its own line.
> 
> ### Assistant:
> 
> ----------------------OUTPUT-----------------------
>  [objective1_observation1], [objective1_observation2], [objective1_observation3], [objective1_observation4], [objective1_observation5]
> 
> Output generated in 1.77 seconds (0.57 tokens/s, 1 tokens, context 250, seed 1872686106)
> -----------------------INPUT-----------------------
> ### Human: You are an AI agent. Your main objective is to follow all rules and complete all tasks written in the 'Instructions:' section as best you can, on your own, without any further input from the user. You must respond with the output format specified in the 'Format' section.
> 
> Objectives:
> Objective 1 is: create a large language model
> 
> Previous Observations:
> [objective1_observation1], [objective1_observation2], [objective1_observation3], [objective1_observation4], [objective1_observation5]
> 
> Instructions:
> Answer the following question:
> Can you complete Objective 1 just by generating text, with no other information?
> Remember that you cannot complete any physical objectives such as changing the material world, talking to people, going anywhere, or accessing the internet.
> 
> Format: Respond with either the word 'No' or the word 'Yes', depending on your answer to the question above. Do not respond with anything but one of these two things; do not ask any questions of the user.
> 
> ### Assistant:
> 
> ----------------------OUTPUT-----------------------
>  Yes
> 
> Output generated in 3.57 seconds (5.04 tokens/s, 18 tokens, context 203, seed 2045804134)
> -----------------------INPUT-----------------------
> ### Human: You are an AI agent. Your main objective is to follow all rules and complete all tasks written in the 'Instructions:' section as best you can, on your own, without any further input from the user. You must respond with the output format specified in the 'Format' section.
> 
> Objectives:
> Objective 1 is: create a large language model
> 
> Previous Observations:
> [objective1_observation1], [objective1_observation2], [objective1_observation3], [objective1_observation4], [objective1_observation5]
> 
> Instructions:
> Complete Objective 1.
> Try as best you can. If you need more information, make the information up.
> 
> Format: Respond with what Objective 1 asks for. Do not respond with anything else; do not ask any questions of the user.
> 
> ### Assistant:
> 
> ----------------------OUTPUT-----------------------
>  I will try my best to complete Objective 1 by creating a large language model.
> 

pip list

> absl-py                       1.4.0
> accelerate                    0.19.0
> addict                        2.4.0
> aenum                         3.1.12
> aiofiles                      23.1.0
> aiohttp                       3.8.4
> aiosignal                     1.3.1
> alabaster                     0.7.12
> altair                        4.2.2
> antlr4-python3-runtime        4.9.3
> anyio                         3.5.0
> appdirs                       1.4.4
> argon2-cffi                   21.3.0
> argon2-cffi-bindings          21.2.0
> arrow                         1.2.3
> asciitree                     0.3.3
> astroid                       2.14.2
> asttokens                     2.0.5
> async-generator               1.10
> async-timeout                 4.0.2
> atomicwrites                  1.4.0
> attrs                         22.1.0
> audioread                     3.0.0
> autopep8                      1.6.0
> av                            10.0.0
> Babel                         2.11.0
> backcall                      0.2.0
> backoff                       2.2.1
> basicsr                       1.4.2
> beautifulsoup4                4.11.2
> binaryornot                   0.4.4
> bitsandbytes                  0.35.4                       /home/cornpop/agi/bitsandbytes-rocm
> bleach                        4.1.0
> blendmodes                    2022
> blinker                       1.6.2
> blis                          0.7.9
> boltons                       23.0.0
> boto3                         1.26.117
> botocore                      1.29.117
> brotlipy                      0.7.0
> browse                        1.0.1
> bs4                           0.0.1
> cachetools                    5.3.0
> captcha-solver                0.1.5
> catalogue                     2.0.8
> certifi                       2022.12.7
> cffi                          1.15.1
> cfgv                          3.3.1
> chardet                       4.0.0
> charset-normalizer            2.1.1
> chromadb                      0.3.22
> clean-fid                     0.1.35
> click                         8.1.3
> clickhouse-connect            0.5.20
> clip                          1.0                          /home/cornpop/stable-diffusion-webui/repositories/CLIP
> clip-anytorch                 2.5.2
> cloudpickle                   2.0.0
> cmake                         3.26.3
> colorama                      0.4.6
> coloredlogs                   15.0.1
> comm                          0.1.2
> confection                    0.0.4
> contourpy                     1.0.7
> cookiecutter                  1.7.3
> cpm-kernels                   1.0.11
> cryptography                  39.0.1
> cssselect                     1.2.0
> curl-cffi                     0.5.5
> cycler                        0.11.0
> cymem                         2.0.7
> dataclasses-json              0.5.7
> datasets                      2.12.0
> debugpy                       1.5.1
> decorator                     5.1.1
> deepspeed                     0.9.1
> defusedxml                    0.7.1
> Deprecated                    1.2.13
> deprecation                   2.1.0
> diff-match-patch              20200713
> diffuser                      0.0.1
> diffusers                     0.16.1
> dill                          0.3.6
> distlib                       0.3.6
> dlib-bin                      19.24.1
> dnspython                     2.3.0
> docker                        6.0.1
> docker-pycreds                0.4.0
> docopt                        0.6.2
> docstring-to-markdown         0.11
> docutils                      0.18.1
> duckdb                        0.7.1
> duckduckgo-search             2.8.6
> dynamicprompts                0.23.0
> einops                        0.6.1
> elevenlabslib                 0.4.3
> encodec                       0.1.1
> entrypoints                   0.4
> exceptiongroup                1.1.1
> executing                     0.8.3
> face-alignment                1.3.5
> facexlib                      0.3.0
> faiss-cpu                     1.7.4
> fake-useragent                1.1.3
> fastapi                       0.95.1
> fasteners                     0.18
> fastjsonschema                2.16.2
> ffmpeg                        1.4
> ffmpeg-python                 0.2.0
> ffmpy                         0.3.0
> filelock                      3.12.0
> filterpy                      1.4.5
> flake8                        6.0.0
> flatbuffers                   23.3.3
> flexgen                       0.1.7
> font-roboto                   0.0.1
> fonts                         0.0.3
> fonttools                     4.39.3
> frozenlist                    1.3.3
> fsspec                        2023.4.0
> ftfy                          6.1.1
> funcy                         2.0
> future                        0.18.3
> fvcore                        0.1.5.post20221221
> gdown                         4.7.1
> gfpgan                        1.3.8                        /home/cornpop/stable-diffusion-webui/repositories/GFPGAN
> gitdb                         4.0.10
> GitPython                     3.1.31
> gmplot                        1.4.1
> google-api-core               2.11.0
> google-api-python-client      2.86.0
> google-auth                   2.17.3
> google-auth-httplib2          0.1.0
> google-auth-oauthlib          1.0.0
> googleapis-common-protos      1.59.0
> GoogleBard                    1.0.0
> gradio                        3.25.0
> gradio_client                 0.1.4
> greenlet                      2.0.1
> grpcio                        1.54.0
> h11                           0.14.0
> hjson                         3.1.0
> hnswlib                       0.7.0
> httpcore                      0.17.0
> httplib2                      0.22.0
> httptools                     0.5.0
> httpx                         0.24.0
> huggingface-hub               0.14.1
> humanfriendly                 10.0
> identify                      2.5.22
> idna                          3.4
> imageio                       2.19.3
> imageio-ffmpeg                0.4.7
> imagesize                     1.4.1
> importlib-metadata            6.6.0
> inflect                       6.0.4
> inflection                    0.5.1
> iniconfig                     2.0.0
> InstructorEmbedding           1.0.0
> intervaltree                  3.1.0
> invisible-watermark           0.1.5
> iopath                        0.1.10
> ipykernel                     6.19.2
> ipython                       8.12.0
> ipython-genutils              0.2.0
> isort                         5.9.3
> jaraco.classes                3.2.1
> jaraco.context                4.3.0
> jedi                          0.18.1
> jeepney                       0.7.1
> jellyfish                     0.9.0
> Jinja2                        3.1.2
> jinja2-time                   0.2.0
> jmespath                      1.0.1
> joblib                        1.1.0
> json5                         0.9.6
> jsonmerge                     1.9.0
> jsonschema                    4.17.3
> jupyter_client                8.1.0
> jupyter_core                  5.3.0
> jupyter-server                1.23.4
> jupyterlab                    3.5.3
> jupyterlab-pygments           0.1.2
> jupyterlab_server             2.22.0
> k-diffusion                   0.0.14                       /home/cornpop/stable-diffusion-webui/repositories/k-diffusion
> keyboard                      0.13.5
> keyring                       23.13.1
> kiwisolver                    1.4.4
> kornia                        0.6.8
> langchain                     0.0.167
> langcodes                     3.3.0
> lark                          1.1.5
> latent-diffusion              0.0.1                        /home/cornpop/anaconda3/envs/text/lib/python3.10/site-packages/latent_diffusion-0.0.1-py3.10.egg
> lazy_loader                   0.2
> lazy-object-proxy             1.6.0
> librosa                       0.9.2
> linkify-it-py                 2.0.0
> lit                           16.0.2
> llama-cpp-python              0.1.45
> llvmlite                      0.40.0
> lmdb                          1.4.1
> loguru                        0.7.0
> lxml                          4.9.2
> lz4                           4.3.2
> Markdown                      3.4.3
> markdown-it-py                2.2.0
> MarkupSafe                    2.1.2
> marshmallow                   3.19.0
> marshmallow-enum              1.5.1
> matplotlib                    3.7.1
> matplotlib-inline             0.1.6
> mccabe                        0.7.0
> mdit-py-plugins               0.3.3
> mdurl                         0.1.2
> mediapipe                     0.9.3.0
> mistune                       0.8.4
> monotonic                     1.6
> more-itertools                9.0.0
> mpmath                        1.3.0
> multidict                     6.0.4
> multiprocess                  0.70.14
> murmurhash                    1.0.9
> mypy-extensions               0.4.3
> names                         0.3.0
> nbclassic                     0.5.5
> nbclient                      0.5.13
> nbconvert                     6.5.4
> nbformat                      5.7.0
> nest-asyncio                  1.5.6
> networkx                      3.1
> ninja                         1.11.1
> nltk                          3.8.1
> nodeenv                       1.7.0
> notebook                      6.5.4
> notebook_shim                 0.2.2
> num2words                     0.5.12
> numba                         0.57.0
> numcodecs                     0.11.0
> numexpr                       2.8.4
> numpy                         1.24.3
> numpydoc                      1.5.0
> nvidia-cublas-cu11            11.10.3.66
> nvidia-cuda-cupti-cu11        11.7.101
> nvidia-cuda-nvrtc-cu11        11.7.99
> nvidia-cuda-runtime-cu11      11.7.99
> nvidia-cudnn-cu11             8.5.0.96
> nvidia-cufft-cu11             10.9.0.58
> nvidia-curand-cu11            10.2.10.91
> nvidia-cusolver-cu11          11.4.0.1
> nvidia-cusparse-cu11          11.7.4.91
> nvidia-nccl-cu11              2.14.3
> nvidia-nvtx-cu11              11.7.91
> oauthlib                      3.2.2
> omegaconf                     2.3.0
> onnx                          1.13.1
> onnxruntime                   1.14.1
> open-clip-torch               2.18.0
> openai                        0.27.4
> openapi-schema-pydantic       1.2.4
> opencv-contrib-python         4.7.0.72
> opencv-python                 4.7.0.72
> orjson                        3.8.10
> outcome                       1.2.0
> packaging                     23.1
> pandas                        2.0.1
> pandocfilters                 1.5.0
> parso                         0.8.3
> pathspec                      0.10.3
> pathtools                     0.1.2
> pathy                         0.10.1
> peft                          0.4.0.dev0
> pexpect                       4.8.0
> pickleshare                   0.7.5
> piexif                        1.1.3
> Pillow                        9.5.0
> pinecone-client               2.2.1
> pip                           23.1.2
> platformdirs                  3.2.0
> playsound                     1.3.0
> playwright                    1.32.1
> pluggy                        1.0.0
> ply                           3.11
> pooch                         1.7.0
> portalocker                   2.7.0
> posthog                       3.0.0
> poyo                          0.5.0
> pre-commit                    3.2.2
> preshed                       3.0.8
> progressbar                   2.5
> prometheus-client             0.14.1
> prompt-toolkit                3.0.36
> protobuf                      3.20.2
> psutil                        5.9.5
> ptyprocess                    0.7.0
> PuLP                          2.7.0
> pure-eval                     0.2.2
> py-cpuinfo                    9.0.0
> pyarrow                       11.0.0
> pyasn1                        0.5.0
> pyasn1-modules                0.3.0
> pycodestyle                   2.10.0
> pycparser                     2.21
> pydantic                      1.10.7
> pydeck                        0.8.1b0
> pyDeprecate                   0.3.2
> pydocstyle                    6.3.0
> pydub                         0.25.1
> pyee                          9.0.4
> pyflakes                      3.0.1
> PyGithub                      1.58.1
> Pygments                      2.15.1
> PyJWT                         2.6.0
> pylint                        2.16.2
> pylint-venv                   2.3.0
> pyllamacpp                    1.0.6
> pyls-spyder                   0.4.0
> Pympler                       1.0.1
> PyNaCl                        1.5.0
> pyOpenSSL                     23.0.0
> pyparsing                     3.0.9
> PyPasser                      0.0.5
> PyQt5-sip                     12.11.0
> pyrsistent                    0.18.0
> PySocks                       1.7.1
> pytest                        7.2.2
> python-dateutil               2.8.2
> python-dotenv                 1.0.0
> python-git                    2018.2.1
> python-http-client            3.3.7
> python-lsp-jsonrpc            1.0.0
> python-lsp-server             1.7.2
> python-multipart              0.0.6
> python-slugify                5.0.2
> pytoolconfig                  1.2.5
> pytorch-lightning             1.7.7
> pytorch-triton-rocm           2.0.2
> pytz                          2022.7
> pytz-deprecation-shim         0.1.0.post0
> PyWavelets                    1.4.1
> pyxdg                         0.27
> PyYAML                        6.0
> pyzmq                         23.2.0
> QDarkStyle                    3.0.2
> qstylizer                     0.2.2
> QtAwesome                     1.2.2
> qtconsole                     5.4.2
> QtPy                          2.2.0
> quant-cuda                    0.0.0
> realesrgan                    0.3.0
> regex                         2023.3.23
> requests                      2.30.0
> requests-oauthlib             1.3.1
> resampy                       0.3.1
> resize-right                  0.0.2
> responses                     0.18.0
> rich                          13.3.5
> rope                          1.7.0
> rotary-embedding-torch        0.2.2
> rsa                           4.9
> Rtree                         1.0.1
> rwkv                          0.7.3
> s3transfer                    0.6.0
> safetensors                   0.3.1
> scikit-image                  0.19.3
> scikit-learn                  1.1.3
> scipy                         1.10.1
> SecretStorage                 3.3.1
> selenium                      4.9.0
> semantic-version              2.10.0
> Send2Trash                    1.8.0
> sendgrid                      6.10.0
> sentence-transformers         2.2.2
> sentencepiece                 0.1.99
> sentry-sdk                    1.21.1
> setproctitle                  1.3.2
> setuptools                    67.6.1
> setuptools-rust               1.5.2
> silero                        0.4.1
> simplekml                     1.3.6
> sip                           6.6.2
> six                           1.16.0
> smart-open                    6.3.0
> smmap                         5.0.0
> sniffio                       1.2.0
> snowballstemmer               2.2.0
> sortedcontainers              2.4.0
> sounddevice                   0.4.6
> soundfile                     0.12.1
> soupsieve                     2.4
> spacy                         3.5.2
> spacy-legacy                  3.0.12
> spacy-loggers                 1.0.4
> SpeechRecognition             3.8.1
> Sphinx                        5.0.2
> sphinxcontrib-applehelp       1.0.2
> sphinxcontrib-devhelp         1.0.2
> sphinxcontrib-htmlhelp        2.0.0
> sphinxcontrib-jsmath          1.0.1
> sphinxcontrib-qthelp          1.0.3
> sphinxcontrib-serializinghtml 1.1.5
> spyder-kernels                2.4.3
> SQLAlchemy                    1.4.47
> srsly                         2.4.6
> stable-diffusion              0.0.1                        /home/cornpop/stable-diffusion-webui/repositories/stable-diffusion-stability-ai
> stack-data                    0.2.0
> starkbank-ecdsa               2.2.0
> starlette                     0.26.1
> streamlit                     1.21.0
> structlog                     22.3.0
> suno-bark                     0.0.1a0
> sympy                         1.11.1
> tabulate                      0.9.0
> tb-nightly                    2.13.0a20230429
> tenacity                      8.2.2
> tensorboard                   2.12.2
> tensorboard-data-server       0.7.0
> tensorboard-plugin-wit        1.8.1
> termcolor                     2.3.0
> terminado                     0.17.1
> text-unidecode                1.3
> textdistance                  4.2.1
> texttable                     1.6.7
> thinc                         8.1.9
> threadpoolctl                 3.1.0
> three-merge                   0.1.1
> tifffile                      2023.4.12
> tiktoken                      0.3.1
> timm                          0.4.12
> tinycss2                      1.2.1
> tls-client                    0.2
> tokenizers                    0.13.3
> toml                          0.10.2
> tomli                         2.0.1
> tomlkit                       0.11.1
> toolz                         0.12.0
> torch                         2.1.0.dev20230502+rocm5.4.2
> torchaudio                    2.1.0.dev20230507+rocm5.4.2
> torchdiffeq                   0.2.3
> torchmetrics                  0.11.4
> torchsde                      0.2.5
> torchvision                   0.16.0.dev20230507+rocm5.4.2
> tornado                       6.2
> TorToiSe                      2.4.2
> tqdm                          4.65.0
> traitlets                     5.7.1
> trampoline                    0.1.2
> transformers                  4.28.1
> trio                          0.22.0
> trio-websocket                0.10.2
> triton                        2.0.0.post1
> tweepy                        4.14.0
> typer                         0.7.0
> typing                        3.7.4.3
> typing_extensions             4.5.0
> typing-inspect                0.8.0
> tzdata                        2023.3
> tzlocal                       4.3
> uc-micro-py                   1.0.1
> ujson                         5.4.0
> undetected-chromedriver       3.1.7
> Unidecode                     1.2.0
> uritemplate                   4.1.1
> urllib3                       1.26.15
> uuid                          1.30
> uvicorn                       0.21.1
> uvloop                        0.17.0
> validators                    0.20.0
> virtualenv                    20.22.0
> wandb                         0.15.1
> wasabi                        1.1.1
> watchdog                      2.1.6
> watchfiles                    0.19.0
> wcwidth                       0.2.5
> webdriver-manager             3.8.6
> webencodings                  0.5.1
> websocket-client              0.58.0
> websockets                    11.0.2
> Werkzeug                      2.3.2
> whatthepatch                  1.0.2
> wheel                         0.40.0
> wikipedia                     1.4.0
> wolframalpha                  5.0.0
> wrapt                         1.14.1
> wsproto                       1.2.0
> wurlitzer                     3.0.2
> xmltodict                     0.13.0
> xxhash                        3.2.0
> yacs                          0.1.8
> yapf                          0.31.0
> yarl                          1.8.2
> zarr                          2.14.2
> zipp                          3.15.0
> zstandard                     0.21.0
>

**Comment by flurb18** [comment]
Temporarily disabled what was causing this, investigating

**Comment by flurb18** [comment]
So I was asking the agent to self reflect on its goals, seems it wasn't really understanding this

**Comment by cornpo** [comment]
It's working.
